# Key concepts related to Chemical Reactors Design {#intro}

In a homogeneous system, the rate of a chemical reaction can be easily estimated because it depends on the temperature system and the concentrations of both reactants and products. However, the prediction on heterogeneous systems is more complicated because of the effect of mass and heat transfer rate over the reaction rate.

## Fundamental of Kinetics and Reaction Equilibrium

It is essential to review some definitions related to design a chemical reactor before starting with our main subject. The first one is **reaction rate**. For a homogeneous reaction, the reaction rate is defined either as the amount of product formed or the amount of reactant consumed per unit volume of the liquid or gas phase per unit time.

\begin{equation*}
  r \equiv \frac{\text{moles consumed or produced}}{\text{reactor volume} \times \text{time}}
\end{equation*}

The reaction rate is based on moles of reactant consumed or produced per unit mass of catalyst per unit time for solid-catalyzed reactions.

\begin{equation*}
    r \equiv \frac{\text{moles consumed or produced}}{\text{mass of catalyst} \times \text{time}}
\end{equation*}

The second important is **conversion**, $X$, which is defined as the fraction of the more critical or limiting reactant consumed. 

\begin{equation*}
X_A \equiv \frac{\text{moles A reacted}}{\text{moles of A fed}}
\end{equation*}

The **yield** is the quantity created by the desired product compared to the quantity that would have been generated if there were no by-products and the primary reaction was completed.

\begin{equation*}
Y \equiv \frac{\text{moles of product formed}}{\text{maximum moles of product},\,X=1.0}
\end{equation*}

For $nA \rightarrow B$

\begin{equation*}
Y \equiv \frac{F_B}{F_A/n}
\end{equation*}

Finally, the **selectivity** is the amount of desired product divided by the amount of reactant consumed. This ratio often changes as the reaction progresses, and the selectivity based on the final mixture composition should be called an _average selectivity_.

For $nA \rightarrow B$
\begin{equation*}
\overline{S} = \frac{\text{B formed}}{\text{A used}} = \frac{F_B}{F_A\,X_A/n} = \frac{Y}{X_A}
\end{equation*}

### Power-Law Kinetics

#### Irreversible Reaction
For an irreversible reaction where two reactants forming a product
\begin{equation*}
A + B \rightarrow C
\end{equation*}

- The overall reaction rate $r$ can be expressed as the moles of components A being consumed per unit time per unit volume.
- Additionally, the overall reaction rate has a temperature dependence governed by the specific reaction rate $k(T)$ and a concentration dependence.

In terms of molar concentrations for components $A$ and $B$, the overall rate reaction could be expressed as:

\begin{equation*}
    r = k(T)\,C_A^\alpha\,C_B^\beta
\end{equation*}
where $\alpha$ and $\beta$ are the order of reaction for each reactants.

The actual reaction mechanism determines the form of the kinetic expression. 

- More than one mechanism may provide the same expression of the rate. 
- Only in elementary reaction steps the reaction order equal to the stoichiometry.

The temperature-dependent specific reaction $k(T)$ is represented by Arrhenius equation
\begin{equation*}
  k(T) = k_0(T) \exp\left[{\left(-E/R/T\right)}\right]
\end{equation*}
where $k0(T)$ is the pre-exponential factor, usually a big positive number that has units with respect to each component based on the concentration units and the order of the reaction, $E$ is the activation energy, $R$ is the universal gas-constant, and $T$ is the absolute temperature.

If $n = \alpha + \beta$ then
\begin{equation*}
  k(T) = \frac{\left[\text{Concentration}^{\left(1-n\right)}\right]}{\text{time}}
\end{equation*}

It is essential to know that:

1. If temperature increase the $k_0(T)$ will be increased.
2. $k_0(T)$ will be more sensitive to temperature changes at higher activation energy.
