# Ideal Chemical Reactor Design

Process design has to do with specific matters relating to the process itself, in our cases, such as operation conditions, size, configuration, and operation mode of the reactor. 

```{r mindmap, out.width = "80%", echo=FALSE, fig.align='center', fig.cap='Conceptual Map of Chemical Reactor Design', fig.lp='fig:'}
library(png)
library(grid)
img <- readPNG("figures/Reactor_Design_map.png")
grid.raster(img)
```

In this course, we will focus on the phenomena taking place in basic reactor types.

The phenomena occurring in a reactor may be broken down into reaction, mass, heat, and momentum transfer. Therefore, reactors' modeling and design are based on the reaction rate equation, the continuity, energy, and momentum equations. The modeling and design of reactors are based on the equations describing these phenomena: the reaction rate equation and the continuity, energy, and momentum equations [@froment2011]. 

Additionally, we will study two situations (1) the design of a new chemical reactor for a new process, (2) the analysis of the performance of an existing reactor for a current process. In many cases, as chemical engineers, we must consider several items shown in figure \@ref(fig:mindmap) when starts the design or analysis of a reactor. 

